-- Catálogos públicos (somente leitura para o app).
-- Proteína por porção: valores aproximados (Tabela TACO / rótulos usuais). Rodar uma vez.

insert into public.foods (name, portion_label, protein_g) values
  -- Carnes e aves
  ('Peito de frango grelhado', '1 filé médio (100 g)', 32),
  ('Frango desfiado', '3 col. sopa (60 g)', 18),
  ('Coxa de frango assada sem pele', '1 unidade (90 g)', 24),
  ('Sobrecoxa de frango assada', '1 unidade (100 g)', 25),
  ('Coração de frango grelhado', '5 unidades (60 g)', 13),
  ('Frango à parmegiana', '1 filé (150 g)', 30),
  ('Carne moída refogada (patinho)', '3 col. sopa (75 g)', 26),
  ('Bife de alcatra grelhado', '1 bife médio (100 g)', 32),
  ('Contrafilé grelhado', '1 bife médio (100 g)', 32),
  ('Picanha grelhada', '1 fatia (100 g)', 27),
  ('Carne de panela (acém)', '1 pedaço (100 g)', 27),
  ('Fígado bovino grelhado', '1 bife (100 g)', 29),
  ('Carne seca desfiada', '3 col. sopa (60 g)', 16),
  ('Hambúrguer bovino caseiro', '1 unidade (90 g)', 20),
  ('Almôndegas bovinas', '3 unidades (90 g)', 15),
  ('Lombo de porco assado', '1 fatia (100 g)', 32),
  ('Bisteca de porco grelhada', '1 unidade (100 g)', 28),
  ('Linguiça toscana grelhada', '1 gomo (60 g)', 11),
  ('Peito de peru fatiado', '2 fatias (30 g)', 6),
  ('Presunto magro', '2 fatias (30 g)', 5),
  ('Mortadela', '2 fatias (30 g)', 4),
  ('Salsicha', '1 unidade (50 g)', 6),
  -- Peixes e frutos do mar
  ('Tilápia grelhada', '1 filé (100 g)', 26),
  ('Salmão grelhado', '1 posta (100 g)', 25),
  ('Merluza cozida', '1 filé (100 g)', 23),
  ('Bacalhau cozido', '1 porção (100 g)', 24),
  ('Sardinha em lata', '1 lata drenada (85 g)', 20),
  ('Atum em lata (em água)', '1/2 lata (60 g)', 15),
  ('Camarão cozido', '10 unidades (100 g)', 24),
  ('Moqueca de peixe', '1 porção (150 g)', 22),
  -- Ovos
  ('Ovo cozido', '1 unidade (50 g)', 6),
  ('Ovo mexido', '1 unidade (50 g)', 6),
  ('Ovo frito', '1 unidade (50 g)', 7),
  ('Omelete simples', '2 ovos (110 g)', 12),
  ('Clara de ovo cozida', '1 clara (33 g)', 4),
  -- Leite e derivados
  ('Leite integral', '1 copo (200 ml)', 6),
  ('Leite desnatado', '1 copo (200 ml)', 6),
  ('Iogurte natural integral', '1 pote (170 g)', 7),
  ('Iogurte grego tradicional', '1 pote (100 g)', 6),
  ('Iogurte proteico', '1 pote (160 g)', 15),
  ('Coalhada', '1 pote (150 g)', 6),
  ('Queijo minas frescal', '1 fatia (30 g)', 5),
  ('Queijo muçarela', '2 fatias (30 g)', 7),
  ('Queijo prato', '2 fatias (30 g)', 7),
  ('Queijo coalho', '1 espeto (60 g)', 14),
  ('Queijo parmesão ralado', '1 col. sopa (10 g)', 4),
  ('Queijo cottage', '2 col. sopa (50 g)', 6),
  ('Ricota', '1 fatia (50 g)', 6),
  ('Requeijão light', '1 col. sopa (30 g)', 3),
  ('Whey protein concentrado', '1 scoop (30 g)', 24),
  ('Shake proteico pronto', '1 garrafa (250 ml)', 15),
  ('Vitamina de banana com leite', '1 copo (300 ml)', 8),
  -- Leguminosas e vegetais proteicos
  ('Feijão carioca cozido', '1 concha (140 g)', 7),
  ('Feijão preto cozido', '1 concha (140 g)', 6),
  ('Feijoada', '1 concha (150 g)', 13),
  ('Lentilha cozida', '1 concha (140 g)', 9),
  ('Grão-de-bico cozido', '3 col. sopa (75 g)', 6),
  ('Ervilha cozida', '3 col. sopa (60 g)', 3),
  ('Soja cozida', '3 col. sopa (60 g)', 10),
  ('Proteína de soja texturizada (hidratada)', '3 col. sopa (60 g)', 9),
  ('Tofu', '1 fatia (100 g)', 8),
  ('Edamame', '1 xícara (100 g)', 12),
  ('Brócolis cozido', '3 ramos (60 g)', 1),
  -- Cereais, pães e massas
  ('Arroz branco cozido', '4 col. sopa (100 g)', 3),
  ('Arroz integral cozido', '4 col. sopa (100 g)', 3),
  ('Macarrão cozido', '1 pegador (110 g)', 5),
  ('Pão francês', '1 unidade (50 g)', 4),
  ('Pão de forma integral', '2 fatias (50 g)', 5),
  ('Pão de queijo', '1 unidade média (40 g)', 2),
  ('Cuscuz de milho', '1 pedaço (100 g)', 2),
  ('Tapioca com queijo', '1 unidade (90 g)', 6),
  ('Aveia em flocos', '2 col. sopa (30 g)', 4),
  ('Granola', '3 col. sopa (40 g)', 4),
  ('Coxinha de frango', '1 unidade (80 g)', 8),
  -- Oleaginosas e sementes
  ('Amendoim torrado', '1 punhado (30 g)', 8),
  ('Pasta de amendoim', '1 col. sopa (15 g)', 4),
  ('Castanha-do-pará', '3 unidades (12 g)', 2),
  ('Castanha de caju', '10 unidades (20 g)', 4),
  ('Amêndoas', '1 punhado (30 g)', 6),
  ('Nozes', '1 punhado (30 g)', 4),
  ('Semente de abóbora', '1 col. sopa (15 g)', 4),
  ('Chia', '1 col. sopa (15 g)', 2);
