-- Catálogos públicos (somente leitura para o app).
-- Proteína por porção: valores aproximados (Tabela TACO / rótulos usuais). Rodar uma vez.

insert into public.foods (name, portion_label, protein_g) values
  -- Carnes e aves
  ('Peito de frango grelhado', '1 filé médio (100 g)', 32),
  ('Frango desfiado', '3 col. sopa (60 g)', 18),
  ('Coxa de frango assada sem pele', '1 unidade (90 g)', 24),
  ('Sobrecoxa de frango assada', '1 unidade (100 g)', 25),
  ('Coração de frango grelhado', '5 unidades (60 g)', 13),
  ('Frango à parmegiana', '1 filé (150 g)', 30),
  ('Carne moída refogada (patinho)', '3 col. sopa (75 g)', 26),
  ('Bife de alcatra grelhado', '1 bife médio (100 g)', 32),
  ('Contrafilé grelhado', '1 bife médio (100 g)', 32),
  ('Picanha grelhada', '1 fatia (100 g)', 27),
  ('Carne de panela (acém)', '1 pedaço (100 g)', 27),
  ('Fígado bovino grelhado', '1 bife (100 g)', 29),
  ('Carne seca desfiada', '3 col. sopa (60 g)', 16),
  ('Hambúrguer bovino caseiro', '1 unidade (90 g)', 20),
  ('Almôndegas bovinas', '3 unidades (90 g)', 15),
  ('Lombo de porco assado', '1 fatia (100 g)', 32),
  ('Bisteca de porco grelhada', '1 unidade (100 g)', 28),
  ('Linguiça toscana grelhada', '1 gomo (60 g)', 11),
  ('Peito de peru fatiado', '2 fatias (30 g)', 6),
  ('Presunto magro', '2 fatias (30 g)', 5),
  ('Mortadela', '2 fatias (30 g)', 4),
  ('Salsicha', '1 unidade (50 g)', 6),
  -- Peixes e frutos do mar
  ('Tilápia grelhada', '1 filé (100 g)', 26),
  ('Salmão grelhado', '1 posta (100 g)', 25),
  ('Merluza cozida', '1 filé (100 g)', 23),
  ('Bacalhau cozido', '1 porção (100 g)', 24),
  ('Sardinha em lata', '1 lata drenada (85 g)', 20),
  ('Atum em lata (em água)', '1/2 lata (60 g)', 15),
  ('Camarão cozido', '10 unidades (100 g)', 24),
  ('Moqueca de peixe', '1 porção (150 g)', 22),
  -- Ovos
  ('Ovo cozido', '1 unidade (50 g)', 6),
  ('Ovo mexido', '1 unidade (50 g)', 6),
  ('Ovo frito', '1 unidade (50 g)', 7),
  ('Omelete simples', '2 ovos (110 g)', 12),
  ('Clara de ovo cozida', '1 clara (33 g)', 4),
  -- Leite e derivados
  ('Leite integral', '1 copo (200 ml)', 6),
  ('Leite desnatado', '1 copo (200 ml)', 6),
  ('Iogurte natural integral', '1 pote (170 g)', 7),
  ('Iogurte grego tradicional', '1 pote (100 g)', 6),
  ('Iogurte proteico', '1 pote (160 g)', 15),
  ('Coalhada', '1 pote (150 g)', 6),
  ('Queijo minas frescal', '1 fatia (30 g)', 5),
  ('Queijo muçarela', '2 fatias (30 g)', 7),
  ('Queijo prato', '2 fatias (30 g)', 7),
  ('Queijo coalho', '1 espeto (60 g)', 14),
  ('Queijo parmesão ralado', '1 col. sopa (10 g)', 4),
  ('Queijo cottage', '2 col. sopa (50 g)', 6),
  ('Ricota', '1 fatia (50 g)', 6),
  ('Requeijão light', '1 col. sopa (30 g)', 3),
  ('Whey protein concentrado', '1 scoop (30 g)', 24),
  ('Shake proteico pronto', '1 garrafa (250 ml)', 15),
  ('Vitamina de banana com leite', '1 copo (300 ml)', 8),
  -- Leguminosas e vegetais proteicos
  ('Feijão carioca cozido', '1 concha (140 g)', 7),
  ('Feijão preto cozido', '1 concha (140 g)', 6),
  ('Feijoada', '1 concha (150 g)', 13),
  ('Lentilha cozida', '1 concha (140 g)', 9),
  ('Grão-de-bico cozido', '3 col. sopa (75 g)', 6),
  ('Ervilha cozida', '3 col. sopa (60 g)', 3),
  ('Soja cozida', '3 col. sopa (60 g)', 10),
  ('Proteína de soja texturizada (hidratada)', '3 col. sopa (60 g)', 9),
  ('Tofu', '1 fatia (100 g)', 8),
  ('Edamame', '1 xícara (100 g)', 12),
  ('Brócolis cozido', '3 ramos (60 g)', 1),
  -- Cereais, pães e massas
  ('Arroz branco cozido', '4 col. sopa (100 g)', 3),
  ('Arroz integral cozido', '4 col. sopa (100 g)', 3),
  ('Macarrão cozido', '1 pegador (110 g)', 5),
  ('Pão francês', '1 unidade (50 g)', 4),
  ('Pão de forma integral', '2 fatias (50 g)', 5),
  ('Pão de queijo', '1 unidade média (40 g)', 2),
  ('Cuscuz de milho', '1 pedaço (100 g)', 2),
  ('Tapioca com queijo', '1 unidade (90 g)', 6),
  ('Aveia em flocos', '2 col. sopa (30 g)', 4),
  ('Granola', '3 col. sopa (40 g)', 4),
  ('Coxinha de frango', '1 unidade (80 g)', 8),
  -- Oleaginosas e sementes
  ('Amendoim torrado', '1 punhado (30 g)', 8),
  ('Pasta de amendoim', '1 col. sopa (15 g)', 4),
  ('Castanha-do-pará', '3 unidades (12 g)', 2),
  ('Castanha de caju', '10 unidades (20 g)', 4),
  ('Amêndoas', '1 punhado (30 g)', 6),
  ('Nozes', '1 punhado (30 g)', 4),
  ('Semente de abóbora', '1 col. sopa (15 g)', 4),
  ('Chia', '1 col. sopa (15 g)', 2);

-- Treinos de força (4 modelos). Sem vídeos no MVP: texto + url opcional.
insert into public.workout_templates (id, name, level, location) values
  (1, 'Corpo todo em casa', 'iniciante', 'casa'),
  (2, 'Corpo todo em casa', 'intermediario', 'casa'),
  (3, 'Corpo todo na academia', 'iniciante', 'academia'),
  (4, 'Corpo todo na academia', 'intermediario', 'academia');
select setval('public.workout_templates_id_seq', 4);

insert into public.workout_template_exercises (template_id, position, name, sets, reps, note) values
  (1, 1, 'Agachamento livre (pode usar uma cadeira atrás)', 3, '12', 'Pés na largura dos ombros, desça com controle.'),
  (1, 2, 'Flexão inclinada com apoio no sofá ou mesa', 3, '10', 'Corpo alinhado, cotovelos perto do tronco.'),
  (1, 3, 'Remada com elástico ou mochila', 3, '12', 'Puxe levando os cotovelos para trás, sem tensionar o pescoço.'),
  (1, 4, 'Ponte de glúteos', 3, '15', 'Suba o quadril contraindo os glúteos, desça devagar.'),
  (1, 5, 'Elevação de panturrilha', 3, '15', 'Apoie-se na parede se precisar.'),
  (1, 6, 'Prancha com joelhos no chão', 3, '20 s', 'Abdômen firme, respire normalmente.'),

  (2, 1, 'Agachamento búlgaro', 3, '10 cada perna', 'Pé de trás apoiado em uma cadeira.'),
  (2, 2, 'Flexão de braço', 3, '10', 'Se precisar, apoie os joelhos.'),
  (2, 3, 'Remada unilateral com mochila ou halter', 3, '12 cada lado', 'Costas retas, apoio em um banco ou cadeira.'),
  (2, 4, 'Afundo alternado', 3, '10 cada perna', 'Passo largo, joelho da frente alinhado com o pé.'),
  (2, 5, 'Elevação pélvica unilateral', 3, '12 cada lado', 'Mantenha o quadril nivelado.'),
  (2, 6, 'Superman', 3, '12', 'Deitado de bruços, eleve braços e pernas juntos.'),
  (2, 7, 'Prancha', 3, '40 s', 'Corpo em linha reta, sem deixar o quadril cair.'),

  (3, 1, 'Leg press', 3, '12', 'Amplitude confortável, sem tirar a lombar do encosto.'),
  (3, 2, 'Puxada alta', 3, '12', 'Puxe a barra até a altura do queixo.'),
  (3, 3, 'Supino na máquina', 3, '12', 'Empurre sem travar os cotovelos.'),
  (3, 4, 'Cadeira flexora', 3, '12', 'Movimento controlado na volta.'),
  (3, 5, 'Remada baixa', 3, '12', 'Peito aberto, ombros longe das orelhas.'),
  (3, 6, 'Prancha', 3, '20 s', 'Abdômen firme, respire normalmente.'),

  (4, 1, 'Agachamento goblet com halter', 4, '10', 'Halter junto ao peito, desça até onde for confortável.'),
  (4, 2, 'Supino com halteres', 4, '10', 'Desça os halteres até a linha do peito.'),
  (4, 3, 'Remada curvada com barra', 4, '10', 'Tronco inclinado e coluna neutra.'),
  (4, 4, 'Levantamento terra romeno', 3, '10', 'Joelhos levemente flexionados, quadril vai para trás.'),
  (4, 5, 'Desenvolvimento com halteres', 3, '10', 'Sem arquear a lombar.'),
  (4, 6, 'Elevação pélvica com barra', 3, '12', 'Pausa de 1 segundo no topo.'),
  (4, 7, 'Prancha', 3, '45 s', 'Corpo em linha reta.');
